// <auto-generated />
using System;
using ArgosSlope.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArgosSlope.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613201407_ConsolidarSchema")]
    partial class ConsolidarSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArgosSlope.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("FisuraId")
                        .HasColumnType("integer")
                        .HasColumnName("fisura_id");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<bool>("Reconocida")
                        .HasColumnType("boolean")
                        .HasColumnName("reconocida");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<double>("UmbralSuperado")
                        .HasColumnType("double precision")
                        .HasColumnName("umbral_superado");

                    b.Property<double>("ValorActual")
                        .HasColumnType("double precision")
                        .HasColumnName("valor_actual");

                    b.HasKey("Id");

                    b.HasIndex("FisuraId");

                    b.ToTable("alerta", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Fisura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision")
                        .HasColumnName("ancho");

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("area");

                    b.Property<bool>("Calibrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("calibrado");

                    b.Property<double>("Confianza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("confianza");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("text")
                        .HasColumnName("coordenadas");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("EstadoAlerta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_alerta");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_deteccion");

                    b.Property<string>("ImagenOriginal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_original");

                    b.Property<string>("ImagenSegmentada")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_segmentada");

                    b.Property<double>("Largo")
                        .HasColumnType("double precision")
                        .HasColumnName("largo");

                    b.Property<string>("Orientacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orientacion");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("real")
                        .HasColumnName("origen");

                    b.Property<string>("RoiId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("roi_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("px")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.ToTable("fisura", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.MedicionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision")
                        .HasColumnName("ancho");

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("area");

                    b.Property<double?>("DeltaPorcentaje")
                        .HasColumnType("double precision")
                        .HasColumnName("delta_porcentaje");

                    b.Property<bool>("EsCritica")
                        .HasColumnType("boolean")
                        .HasColumnName("es_critica");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("FisuraId")
                        .HasColumnType("integer")
                        .HasColumnName("fisura_id");

                    b.Property<double>("Largo")
                        .HasColumnType("double precision")
                        .HasColumnName("largo");

                    b.HasKey("Id");

                    b.HasIndex("FisuraId");

                    b.ToTable("medicion_diaria", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Snapshot3DEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("CrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("crack_count");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<int>("MeshVertexCount")
                        .HasColumnType("integer")
                        .HasColumnName("mesh_vertex_count");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapturedAt");

                    b.ToTable("snapshot_3d", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Alerta", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Fisura", "Fisura")
                        .WithMany("Alertas")
                        .HasForeignKey("FisuraId");

                    b.Navigation("Fisura");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.MedicionDiaria", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Fisura", "Fisura")
                        .WithMany("Mediciones")
                        .HasForeignKey("FisuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fisura");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Fisura", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Mediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
