// <auto-generated />
using System;
using ArgosSlope.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArgosSlope.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614203120_AddGeomechanicsModule")]
    partial class AddGeomechanicsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArgosSlope.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("FisuraId")
                        .HasColumnType("integer")
                        .HasColumnName("fisura_id");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<bool>("Reconocida")
                        .HasColumnType("boolean")
                        .HasColumnName("reconocida");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<double>("UmbralSuperado")
                        .HasColumnType("double precision")
                        .HasColumnName("umbral_superado");

                    b.Property<double>("ValorActual")
                        .HasColumnType("double precision")
                        .HasColumnName("valor_actual");

                    b.HasKey("Id");

                    b.HasIndex("FisuraId");

                    b.ToTable("alerta", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Fisura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision")
                        .HasColumnName("ancho");

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("area");

                    b.Property<bool>("Calibrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("calibrado");

                    b.Property<double>("Confianza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("confianza");

                    b.Property<string>("Coordenadas")
                        .HasColumnType("text")
                        .HasColumnName("coordenadas");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("EstadoAlerta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_alerta");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_deteccion");

                    b.Property<string>("ImagenOriginal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_original");

                    b.Property<string>("ImagenSegmentada")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_segmentada");

                    b.Property<double>("Largo")
                        .HasColumnType("double precision")
                        .HasColumnName("largo");

                    b.Property<string>("Orientacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("orientacion");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("real")
                        .HasColumnName("origen");

                    b.Property<string>("RoiId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("roi_id");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("px")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.ToTable("fisura", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.GeomechanicalEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("ImageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<string>("MonitoringId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("monitoring_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RmrClass")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rmr_class");

                    b.Property<string>("RmrQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rmr_quality");

                    b.Property<int?>("RmrValue")
                        .HasColumnType("integer")
                        .HasColumnName("rmr_value");

                    b.Property<string>("RqdMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rqd_method");

                    b.Property<string>("RqdQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rqd_quality");

                    b.Property<double?>("RqdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("rqd_value");

                    b.Property<string>("ZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.ToTable("geomechanical_evaluations");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.MedicionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision")
                        .HasColumnName("ancho");

                    b.Property<double>("Area")
                        .HasColumnType("double precision")
                        .HasColumnName("area");

                    b.Property<double?>("DeltaPorcentaje")
                        .HasColumnType("double precision")
                        .HasColumnName("delta_porcentaje");

                    b.Property<bool>("EsCritica")
                        .HasColumnType("boolean")
                        .HasColumnName("es_critica");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("FisuraId")
                        .HasColumnType("integer")
                        .HasColumnName("fisura_id");

                    b.Property<double>("Largo")
                        .HasColumnType("double precision")
                        .HasColumnName("largo");

                    b.HasKey("Id");

                    b.HasIndex("FisuraId");

                    b.ToTable("medicion_diaria", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RmrCatalogOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_key");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.ToTable("rmr_catalog_option");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RmrParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_id");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_key");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SelectedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selected_code");

                    b.Property<string>("SelectedLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("selected_label");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("rmr_parameters");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscontinuityCount")
                        .HasColumnType("integer")
                        .HasColumnName("discontinuity_count");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("InputDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_data_json");

                    b.Property<double?>("Jv")
                        .HasColumnType("double precision")
                        .HasColumnName("jv");

                    b.Property<double?>("LambdaValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lambda_value");

                    b.Property<double?>("LineLengthM")
                        .HasColumnType("double precision")
                        .HasColumnName("line_length_m");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<string>("RqdQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rqd_quality");

                    b.Property<double>("RqdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("rqd_value");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("rqd_calculations");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdJointFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DetectedByOpenCv")
                        .HasColumnType("boolean")
                        .HasColumnName("detected_by_opencv");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<double?>("OrientationDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("orientation_deg");

                    b.Property<int>("RqdCalculationId")
                        .HasColumnType("integer")
                        .HasColumnName("rqd_calculation_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<double>("SpacingM")
                        .HasColumnType("double precision")
                        .HasColumnName("spacing_m");

                    b.HasKey("Id");

                    b.HasIndex("RqdCalculationId");

                    b.ToTable("rqd_joint_families");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Snapshot3DEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("CrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("crack_count");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<int>("MeshVertexCount")
                        .HasColumnType("integer")
                        .HasColumnName("mesh_vertex_count");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapturedAt");

                    b.ToTable("snapshot_3d", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Alerta", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Fisura", "Fisura")
                        .WithMany("Alertas")
                        .HasForeignKey("FisuraId");

                    b.Navigation("Fisura");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.MedicionDiaria", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Fisura", "Fisura")
                        .WithMany("Mediciones")
                        .HasForeignKey("FisuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fisura");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RmrParameter", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.GeomechanicalEvaluation", "Evaluation")
                        .WithMany("RmrParameters")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdCalculation", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.GeomechanicalEvaluation", "Evaluation")
                        .WithOne("RqdCalculation")
                        .HasForeignKey("ArgosSlope.Api.Models.RqdCalculation", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdJointFamily", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.RqdCalculation", "RqdCalculation")
                        .WithMany("JointFamilies")
                        .HasForeignKey("RqdCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RqdCalculation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Fisura", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Mediciones");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.GeomechanicalEvaluation", b =>
                {
                    b.Navigation("RmrParameters");

                    b.Navigation("RqdCalculation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdCalculation", b =>
                {
                    b.Navigation("JointFamilies");
                });
#pragma warning restore 612, 618
        }
    }
}
