// <auto-generated />
using System;
using ArgosSlope.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArgosSlope.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArgosSlope.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CrackId")
                        .HasColumnType("integer")
                        .HasColumnName("crack_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<bool>("Reconocida")
                        .HasColumnType("boolean")
                        .HasColumnName("reconocida");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<double>("UmbralSuperado")
                        .HasColumnType("double precision")
                        .HasColumnName("umbral_superado");

                    b.Property<double>("ValorActual")
                        .HasColumnType("double precision")
                        .HasColumnName("valor_actual");

                    b.HasKey("Id");

                    b.HasIndex("CrackId");

                    b.ToTable("alerta", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 760, DateTimeKind.Utc).AddTicks(3343),
                            Description = "Acceso total al sistema",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 760, DateTimeKind.Utc).AddTicks(3346),
                            Description = "Operador de campo",
                            Name = "Operador"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 760, DateTimeKind.Utc).AddTicks(3348),
                            Description = "Ingeniero geotécnico",
                            Name = "Geotécnico"
                        });
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 881, DateTimeKind.Utc).AddTicks(6828),
                            Email = "admin@argos.mine",
                            FullName = "Admin ARGOS",
                            IsActive = true,
                            PasswordHash = "$2a$11$8Ir4uPmCfJ4jQosxB93UEOnbxZ3f/tJmGmUReMJ8xTekKSymthM2G",
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 881, DateTimeKind.Utc).AddTicks(6833)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 881, DateTimeKind.Utc).AddTicks(6862),
                            Email = "operador@argos.mine",
                            FullName = "Operador Campo",
                            IsActive = true,
                            PasswordHash = "$2a$11$8Ir4uPmCfJ4jQosxB93UEOnbxZ3f/tJmGmUReMJ8xTekKSymthM2G",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 881, DateTimeKind.Utc).AddTicks(6862)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 881, DateTimeKind.Utc).AddTicks(6864),
                            Email = "geotecnico@argos.mine",
                            FullName = "Ing. Geotécnico",
                            IsActive = true,
                            PasswordHash = "$2a$11$8Ir4uPmCfJ4jQosxB93UEOnbxZ3f/tJmGmUReMJ8xTekKSymthM2G",
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2026, 6, 17, 11, 25, 20, 881, DateTimeKind.Utc).AddTicks(6865)
                        });
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Capture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OriginalMediaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessedMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ThumbnailMediaId")
                        .HasColumnType("integer");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("capture", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("configuracion", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Crack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("crack", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.CrackDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AreaPx2")
                        .HasColumnType("double precision");

                    b.Property<int>("BboxH")
                        .HasColumnType("integer");

                    b.Property<int>("BboxW")
                        .HasColumnType("integer");

                    b.Property<int>("BboxX")
                        .HasColumnType("integer");

                    b.Property<int>("BboxY")
                        .HasColumnType("integer");

                    b.Property<int?>("CaptureId")
                        .HasColumnType("integer");

                    b.Property<int>("CenterX")
                        .HasColumnType("integer");

                    b.Property<int>("CenterY")
                        .HasColumnType("integer");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("CrackId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<double>("LengthPx")
                        .HasColumnType("double precision");

                    b.Property<string>("MaskPath")
                        .HasColumnType("text");

                    b.Property<double>("OrientationDeg")
                        .HasColumnType("double precision");

                    b.Property<double>("WidthPx")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CaptureId");

                    b.HasIndex("CrackId");

                    b.ToTable("crack_detection", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.CrackMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AreaMm2")
                        .HasColumnType("double precision");

                    b.Property<double>("AreaPx2")
                        .HasColumnType("double precision");

                    b.Property<int?>("CaptureId")
                        .HasColumnType("integer");

                    b.Property<int>("CrackId")
                        .HasColumnType("integer");

                    b.Property<double>("GrowthPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCalibrated")
                        .HasColumnType("boolean");

                    b.Property<double?>("LengthMm")
                        .HasColumnType("double precision");

                    b.Property<double>("LengthPx")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MmPerPixel")
                        .HasColumnType("double precision");

                    b.Property<double?>("WidthMm")
                        .HasColumnType("double precision");

                    b.Property<double>("WidthPx")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CaptureId");

                    b.HasIndex("CrackId");

                    b.ToTable("crack_measurement", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.GeomechanicalEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("ImageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<string>("MonitoringId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("monitoring_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RmrClass")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rmr_class");

                    b.Property<string>("RmrQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rmr_quality");

                    b.Property<int?>("RmrValue")
                        .HasColumnType("integer")
                        .HasColumnName("rmr_value");

                    b.Property<string>("RqdMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rqd_method");

                    b.Property<string>("RqdQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rqd_quality");

                    b.Property<double?>("RqdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("rqd_value");

                    b.Property<string>("ZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.ToTable("geomechanical_evaluations");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.LoginAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAttempted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("login_audit", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RelatedType", "RelatedId");

                    b.ToTable("media_file", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.MonitoringAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("analysis_json");

                    b.Property<string>("AnalysisType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("analysis_type");

                    b.Property<string>("CaptureId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("capture_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBaseImage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base_image");

                    b.Property<string>("ProcessedImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("processed_image_path");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.ToTable("monitoring_analyses");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RmrCatalogOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_key");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.ToTable("rmr_catalog_option");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RmrParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_id");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_key");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SelectedCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selected_code");

                    b.Property<string>("SelectedLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("selected_label");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("rmr_parameters");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscontinuityCount")
                        .HasColumnType("integer")
                        .HasColumnName("discontinuity_count");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("integer")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("InputDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_data_json");

                    b.Property<double?>("Jv")
                        .HasColumnType("double precision")
                        .HasColumnName("jv");

                    b.Property<double?>("LambdaValue")
                        .HasColumnType("double precision")
                        .HasColumnName("lambda_value");

                    b.Property<double?>("LineLengthM")
                        .HasColumnType("double precision")
                        .HasColumnName("line_length_m");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("method");

                    b.Property<string>("RqdQuality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rqd_quality");

                    b.Property<double>("RqdValue")
                        .HasColumnType("double precision")
                        .HasColumnName("rqd_value");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("rqd_calculations");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdJointFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DetectedByOpenCv")
                        .HasColumnType("boolean")
                        .HasColumnName("detected_by_opencv");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<double?>("OrientationDeg")
                        .HasColumnType("double precision")
                        .HasColumnName("orientation_deg");

                    b.Property<int>("RqdCalculationId")
                        .HasColumnType("integer")
                        .HasColumnName("rqd_calculation_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<double>("SpacingM")
                        .HasColumnType("double precision")
                        .HasColumnName("spacing_m");

                    b.HasKey("Id");

                    b.HasIndex("RqdCalculationId");

                    b.ToTable("rqd_joint_families");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Snapshot3DEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("CrackCount")
                        .HasColumnType("integer")
                        .HasColumnName("crack_count");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<int>("MeshVertexCount")
                        .HasColumnType("integer")
                        .HasColumnName("mesh_vertex_count");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("PointCount")
                        .HasColumnType("integer")
                        .HasColumnName("point_count");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "CapturedAt");

                    b.ToTable("snapshot_3d", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Alerta", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Crack", "Crack")
                        .WithMany()
                        .HasForeignKey("CrackId");

                    b.Navigation("Crack");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.AppUser", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.CrackDetection", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Capture", "Capture")
                        .WithMany("Detections")
                        .HasForeignKey("CaptureId");

                    b.HasOne("ArgosSlope.Api.Models.Crack", "Crack")
                        .WithMany("Detections")
                        .HasForeignKey("CrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capture");

                    b.Navigation("Crack");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.CrackMeasurement", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.Capture", "Capture")
                        .WithMany()
                        .HasForeignKey("CaptureId");

                    b.HasOne("ArgosSlope.Api.Models.Crack", "Crack")
                        .WithMany("Measurements")
                        .HasForeignKey("CrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capture");

                    b.Navigation("Crack");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RmrParameter", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.GeomechanicalEvaluation", "Evaluation")
                        .WithMany("RmrParameters")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdCalculation", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.GeomechanicalEvaluation", "Evaluation")
                        .WithOne("RqdCalculation")
                        .HasForeignKey("ArgosSlope.Api.Models.RqdCalculation", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdJointFamily", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.RqdCalculation", "RqdCalculation")
                        .WithMany("JointFamilies")
                        .HasForeignKey("RqdCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RqdCalculation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.UserSession", b =>
                {
                    b.HasOne("ArgosSlope.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Capture", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.Crack", b =>
                {
                    b.Navigation("Detections");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.GeomechanicalEvaluation", b =>
                {
                    b.Navigation("RmrParameters");

                    b.Navigation("RqdCalculation");
                });

            modelBuilder.Entity("ArgosSlope.Api.Models.RqdCalculation", b =>
                {
                    b.Navigation("JointFamilies");
                });
#pragma warning restore 612, 618
        }
    }
}
