"""
ARGOS SLOPE 4.0 — Data Bridge Module.

Reads crack_history.json (generated by the edge pipeline) and provides
data-access functions for the REST API. All state is derived from the
JSON file plus an in-memory acknowledged-alert set.

Envvars:
    CRACK_HISTORY_PATH — path to crack_history.json (default: crack_history.json)
"""

from __future__ import annotations

import json
import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

# ── Module-level state ───────────────────────────────────────────────
_acknowledged_alert_ids: set[int] = set()
_config_overrides: dict[str, str] = {}

CONFIG_DEFAULTS = [
    {"clave": "distancia_focal_mm", "valor": "50", "descripcion": "Distancia focal de la cámara en mm (f)"},
    {"clave": "distancia_sensor_z_mm", "valor": "10000", "descripcion": "Distancia del sensor al talud en mm (Z)"},
    {"clave": "umbral_velocidad_moderada", "valor": "0.5", "descripcion": "Umbral de velocidad moderada (mm/día)"},
    {"clave": "umbral_velocidad_rapida", "valor": "2.0", "descripcion": "Umbral de velocidad rápida (mm/día)"},
    {"clave": "intervalo_polling_seg", "valor": "30", "descripcion": "Intervalo de actualización del dashboard (seg)"},
    # Extra entries the frontend FormularioConfig expects
    {"clave": "umbral_delta_critico", "valor": "5.0", "descripcion": "Porcentaje de crecimiento (Δ) que dispara alerta crítica"},
    {"clave": "tamano_minimo_bloque_rqd_cm", "valor": "10", "descripcion": "Longitud mínima de bloque intacto para cálculo RQD"},
]


# ── Helpers ──────────────────────────────────────────────────────────

def _get_history_path() -> str:
    return os.environ.get("CRACK_HISTORY_PATH", "crack_history.json")


def load_snapshots() -> list[dict]:
    """
    Load all crack snapshots from crack_history.json.

    Returns an empty list if the file does not exist or is malformed.
    """
    path = _get_history_path()
    if not os.path.exists(path):
        logger.debug("crack_history.json not found at %s", path)
        return []
    try:
        with open(path, "r") as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
        logger.warning("Expected JSON list in %s, got %s", path, type(data).__name__)
        return []
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to load crack_history.json: %s", exc)
        return []


def _group_by_track(snapshots: list[dict]) -> dict[int, list[dict]]:
    """Group snapshots by tracking_id, sorted by timestamp ascending."""
    groups: dict[int, list[dict]] = {}
    for snap in snapshots:
        tid = snap.get("tracking_id")
        if tid is None:
            continue
        groups.setdefault(tid, []).append(snap)
    for tid in groups:
        groups[tid].sort(key=lambda s: s.get("timestamp", ""))
    return groups


def _roi_id(track_id: int) -> str:
    """Generate an uppercase-hex ROI identifier like CRK-A1B2C3D4."""
    return f"CRK-{track_id:08X}"


def _get_latest(snapshots: list[dict]) -> dict:
    """Return the latest snapshot (last by timestamp)."""
    return snapshots[-1]


def _get_earliest(snapshots: list[dict]) -> dict:
    """Return the earliest snapshot (first by timestamp)."""
    return snapshots[0]


def _compute_delta_percentage(earliest: dict, latest: dict) -> Optional[float]:
    """Compute (latest - earliest) / earliest * 100 for width_mm."""
    earliest_w = earliest.get("width_mm")
    latest_w = latest.get("width_mm")
    if earliest_w is not None and latest_w is not None and earliest_w != 0:
        return ((latest_w - earliest_w) / earliest_w) * 100.0
    return None


# ── Prediction helpers ──────────────────────────────────────────────

def _linear_regression(
    x: list[float], y: list[float],
) -> tuple[float, float, float]:
    """
    Simple linear regression (pure Python, no numpy).

    Returns (slope, intercept, r_squared).
    """
    n = len(x)
    if n < 3:
        return 0.0, 0.0, 0.0
    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum(xi * yi for xi, yi in zip(x, y))
    sum_x2 = sum(xi * xi for xi in x)
    sum_y2 = sum(yi * yi for yi in y)

    denom = n * sum_x2 - sum_x * sum_x
    if denom == 0:
        return 0.0, 0.0, 0.0

    slope = (n * sum_xy - sum_x * sum_y) / denom
    intercept = (sum_y - slope * sum_x) / n

    # R²
    mean_y = sum_y / n
    ss_res = sum((yi - (slope * xi + intercept)) ** 2 for xi, yi in zip(x, y))
    ss_tot = sum((yi - mean_y) ** 2 for yi in y)
    r_squared = 1.0 - (ss_res / ss_tot) if ss_tot != 0 else 0.0
    r_squared = max(0.0, min(1.0, r_squared))

    return slope, intercept, r_squared


def _classify_trend_direction(
    slope: float, slope_threshold: float = 0.01,
) -> str:
    """Classify slope into acelerando / estable / desacelerando."""
    if slope > slope_threshold:
        return "acelerando"
    if slope < -slope_threshold:
        return "desacelerando"
    return "estable"


def _compute_ttt(
    slope: float,
    intercept: float,
    latest_width: float,
    threshold_width: float = 10.0,
    horizon_days: float = 14.0,
) -> Optional[float]:
    """
    Compute Time-To-Threshold (days) for crack width.

    Returns None when slope <= 0 (not widening).
    Caps result at horizon_days.
    """
    if slope <= 0:
        return None
    # TTT = (threshold - current_width) / slope
    ttt = (threshold_width - latest_width) / slope
    if ttt < 0:
        return None
    return min(ttt, horizon_days)


# ── Public API ───────────────────────────────────────────────────────

def get_fisuras() -> list[dict]:
    """
    Return all fissures with their latest state and computed fields.

    Each entry:
        id, roi_id, fecha_deteccion, largo_mm, ancho_mm, area_mm2,
        orientacion, tipo, coordenadas, delta_porcentaje, es_critica,
        velocidad_mm_day, imagen_original, imagen_segmentada
    """
    snapshots = load_snapshots()
    groups = _group_by_track(snapshots)
    result = []
    for tid in sorted(groups):
        snaps = groups[tid]
        earliest = _get_earliest(snaps)
        latest = _get_latest(snaps)
        velocity = latest.get("velocity_mm_day") or 0.0
        result.append({
            "id": tid,
            "roi_id": _roi_id(tid),
            "fecha_deteccion": earliest.get("timestamp", ""),
            "largo_mm": latest.get("length_mm", 0.0),
            "ancho_mm": latest.get("width_mm", 0.0),
            "area_mm2": latest.get("area_mm2", 0.0),
            "orientacion": None,
            "tipo": latest.get("classification", "none"),
            "coordenadas": None,
            "delta_porcentaje": _compute_delta_percentage(earliest, latest),
            "es_critica": velocity > 2.0,
            "velocidad_mm_day": velocity,
            "imagen_original": None,
            "imagen_segmentada": None,
        })
    return result


def get_fisura(track_id: int) -> Optional[dict]:
    """
    Return a single fissure with full detail including measurements and alerts.

    Returns None if track_id not found.
    """
    snapshots = load_snapshots()
    groups = _group_by_track(snapshots)
    snaps = groups.get(track_id)
    if not snaps:
        return None
    earliest = _get_earliest(snaps)
    latest = _get_latest(snaps)
    velocity = latest.get("velocity_mm_day") or 0.0
    mediciones = get_mediciones(track_id)
    alertas_list = get_alertas()
    fisura_alertas = [a for a in alertas_list if a["fisura_id"] == track_id]
    return {
        "fisura": {
            "id": track_id,
            "roi_id": _roi_id(track_id),
            "fecha_deteccion": earliest.get("timestamp", ""),
            "largo_mm": latest.get("length_mm", 0.0),
            "ancho_mm": latest.get("width_mm", 0.0),
            "area_mm2": latest.get("area_mm2", 0.0),
            "orientacion": None,
            "tipo": latest.get("classification", "none"),
            "coordenadas": None,
            "delta_porcentaje": _compute_delta_percentage(earliest, latest),
            "es_critica": velocity > 2.0,
            "velocidad_mm_day": velocity,
            "imagen_original": None,
            "imagen_segmentada": None,
        },
        "mediciones": mediciones,
        "alertas": fisura_alertas,
        "total_mediciones": len(mediciones),
    }


def get_mediciones(track_id: int, dias: Optional[int] = None) -> list[dict]:
    """
    Return historical measurements for a fissure.

    Each entry: id, fisura_id, fecha, largo_mm, ancho_mm, area_mm2,
    delta_porcentaje, es_critica, velocidad_mm_day.
    """
    snapshots = load_snapshots()
    groups = _group_by_track(snapshots)
    snaps = groups.get(track_id)
    if not snaps:
        return []

    # Filter by days if requested
    if dias is not None and dias > 0:
        from datetime import datetime, timedelta, timezone
        cutoff = datetime.now(timezone.utc) - timedelta(days=dias)
        snaps = [
            s for s in snaps
            if _parse_timestamp(s.get("timestamp", "")) >= cutoff
        ]

    result = []
    prev_width = None
    for idx, snap in enumerate(snaps):
        width = snap.get("width_mm")
        delta_pct = None
        if prev_width is not None and width is not None and prev_width != 0:
            delta_pct = ((width - prev_width) / prev_width) * 100.0
        velocity = snap.get("velocity_mm_day") or 0.0
        result.append({
            "id": idx + 1,
            "fisura_id": track_id,
            "fecha": snap.get("timestamp", ""),
            "largo_mm": snap.get("length_mm", 0.0),
            "ancho_mm": width if width is not None else 0.0,
            "area_mm2": snap.get("area_mm2", 0.0),
            "delta_porcentaje": delta_pct,
            "es_critica": velocity > 2.0,
            "velocidad_mm_day": velocity,
        })
        prev_width = width
    return result


def _parse_timestamp(ts: str):
    """Parse ISO-8601 timestamp, return a datetime. Returns epoch on failure."""
    from datetime import datetime, timezone
    try:
        # Try full ISO format with timezone
        if ts.endswith("Z"):
            return datetime.fromisoformat(ts.replace("Z", "+00:00"))
        if "+" in ts or ts.count("-") > 2:
            return datetime.fromisoformat(ts)
        # Fallback: assume UTC
        return datetime.fromisoformat(ts).replace(tzinfo=timezone.utc)
    except (ValueError, TypeError):
        return datetime(1970, 1, 1, tzinfo=timezone.utc)


def get_alertas(solo_no_reconocidas: bool = False) -> list[dict]:
    """
    Generate alert records from velocity data in crack snapshots.

    An alert is generated for each snapshot where velocity_mm_day is
    NOT null and > umbral_velocidad_moderada (0.5).

    Returns alerts sorted by fecha descending, with reconocida flag
    computed from the module-level acknowledged set.
    """
    snapshots = load_snapshots()
    # Load thresholds from config (or defaults)
    thresholds = _get_thresholds()

    alerts = []
    alert_idx = 0
    for snap in snapshots:
        velocity = snap.get("velocity_mm_day")
        if velocity is None or velocity <= thresholds["moderada"]:
            continue

        alert_idx += 1
        tid = snap.get("tracking_id", 0)
        rid = _roi_id(tid)
        cat = "critico" if velocity > thresholds["rapida"] else "advertencia"
        mensaje = (
            f"Velocidad de deformación {cat} en fisura {rid}: "
            f"{velocity:.2f} mm/día"
        )

        alerts.append({
            "id": alert_idx,
            "fisura_id": tid,
            "fecha": snap.get("timestamp", ""),
            "tipo": cat,
            "mensaje": mensaje,
            "umbral_superado": thresholds["rapida"] if cat == "critico" else thresholds["moderada"],
            "valor_actual": velocity,
            "reconocida": alert_idx in _acknowledged_alert_ids,
        })

    # Sort by fecha descending
    alerts.sort(key=lambda a: a.get("fecha", ""), reverse=True)

    if solo_no_reconocidas:
        alerts = [a for a in alerts if not a["reconocida"]]

    return alerts


def _get_thresholds() -> dict:
    """Return velocity thresholds from config or defaults."""
    vals = {}
    for entry in CONFIG_DEFAULTS:
        clave = entry["clave"]
        override = _config_overrides.get(clave)
        vals[clave] = override if override is not None else entry["valor"]
    return {
        "moderada": float(vals.get("umbral_velocidad_moderada", 0.5)),
        "rapida": float(vals.get("umbral_velocidad_rapida", 2.0)),
    }


def reconocer_alerta(alerta_id: int) -> Optional[dict]:
    """
    Mark an alert as acknowledged.

    Returns the updated alert or None if alert_id not found.
    """
    alerts = get_alertas()
    target = None
    for a in alerts:
        if a["id"] == alerta_id:
            target = a
            break
    if target is None:
        return None
    _acknowledged_alert_ids.add(alerta_id)
    target["reconocida"] = True
    return target


def get_resumen() -> dict:
    """
    Dashboard summary.

    Returns:
        total_fisuras, alertas_criticas, rpi_conectada, deformacion_promedio
    """
    snapshots = load_snapshots()
    groups = _group_by_track(snapshots)
    unique_ids = list(groups.keys())

    total_fisuras = len(unique_ids)

    # Count critical alerts (velocity > 2.0)
    alerts = get_alertas()
    alertas_criticas = sum(1 for a in alerts if a["tipo"] == "critico")

    # Average of latest velocity across all fissures
    velocities = []
    for tid in unique_ids:
        latest = _get_latest(groups[tid])
        v = latest.get("velocity_mm_day")
        if v is not None:
            velocities.append(v)
    deformacion_promedio = sum(velocities) / len(velocities) if velocities else 0.0

    return {
        "total_fisuras": total_fisuras,
        "alertas_criticas": alertas_criticas,
        "rpi_conectada": True,
        "deformacion_promedio": deformacion_promedio,
        "count_predicciones_activas": len(get_predicciones()),
    }


# ── Prediction API ──────────────────────────────────────────────────

def get_predicciones() -> list[dict]:
    """
    Compute trend predictions from crack width measurements.

    For each crack with at least 3 data points, runs simple linear
    regression on width_mm over time.

    Returns:
        List of dicts:
            crack_id, trend_direction, slope, r_squared,
            ttt_days, confidence, latest_width
    """
    snapshots = load_snapshots()
    groups = _group_by_track(snapshots)
    results: list[dict] = []

    for tid in sorted(groups):
        snaps = groups[tid]
        if len(snaps) < 3:
            continue

        # Convert timestamps to days elapsed from first measurement
        first_ts = _parse_timestamp(snaps[0].get("timestamp", ""))
        days: list[float] = []
        widths: list[float] = []
        for snap in snaps:
            ts = _parse_timestamp(snap.get("timestamp", ""))
            delta = (ts - first_ts).total_seconds() / 86400.0  # seconds → days
            w = snap.get("width_mm")
            if w is not None and delta >= 0:
                days.append(delta)
                widths.append(float(w))

        if len(days) < 3:
            continue

        slope, intercept, r_squared = _linear_regression(days, widths)
        trend_direction = _classify_trend_direction(slope)
        latest_width = widths[-1] if widths else 0.0

        # TTT: use the configurable threshold (default 10.0 mm)
        thresholds = _get_thresholds()
        threshold_width = 10.0  # mm — reasonable default for critical width
        ttt_days = _compute_ttt(slope, intercept, latest_width, threshold_width)

        confidence = max(0.0, min(1.0, r_squared))

        results.append({
            "crack_id": tid,
            "roi_id": _roi_id(tid),
            "trend_direction": trend_direction,
            "slope": round(slope, 6),
            "r_squared": round(r_squared, 4),
            "ttt_days": round(ttt_days, 1) if ttt_days is not None else None,
            "confidence": round(confidence, 4),
            "latest_width_mm": round(latest_width, 3),
            "threshold_width_mm": threshold_width,
            "total_mediciones": len(days),
        })

    return results


def get_prediccion(track_id: int) -> Optional[dict]:
    """Return prediction for a single crack, or None if not found."""
    predictions = get_predicciones()
    for p in predictions:
        if p["crack_id"] == track_id:
            return p
    return None


def get_configuracion() -> list[dict]:
    """Return config entries with any in-memory overrides applied."""
    result = []
    for entry in CONFIG_DEFAULTS:
        clave = entry["clave"]
        override = _config_overrides.get(clave)
        result.append({
            "clave": clave,
            "valor": override if override is not None else entry["valor"],
            "descripcion": entry["descripcion"],
        })
    return result


def actualizar_configuracion(clave: str, valor: str) -> dict:
    """Update a single config value in memory."""
    _config_overrides[clave] = valor
    return {"clave": clave, "valor": valor, "ok": True}
